// <auto-generated />
namespace Password_Reset.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class loginmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201912021341284_loginmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
